importReact,{useState,useMemo}from'react';
import{useNavigate}from'react-router-dom';
import{
Users,AlertTriangle,ShieldCheck,AlertCircle,Eye,Search,ChevronLeft,ChevronRight
}from'lucide-react';
import{
students,allRiskScores,
getRiskDistribution,getRiskFactorsData,getRiskSummary
}from'../../data/mockData';
import{RISK_LEVEL_INFO}from'../../utils/calculations';
importDonutChartfrom'../../components/charts/DonutChart';
importBarChartComponentfrom'../../components/charts/BarChart';

//InlineComponents
constSummaryCard=({icon:Icon,title,value,subtitle,color}:{icon:any,title:string,value:string|number,subtitle?:string,color:string})=>(
<divclassName="bg-whiterounded-xlshadow-smborderborder-gray-100p-6">
<divclassName="flexitems-centergap-4">
<divclassName={`w-12h-12rounded-xlflexitems-centerjustify-center${color}`}>
<IconclassName="w-6h-6text-white"/>
</div>
<div>
<pclassName="text-smtext-gray-500">{title}</p>
<pclassName="text-2xlfont-boldtext-gray-800">{value}</p>
{subtitle&&<pclassName="text-xstext-gray-400mt-0.5">{subtitle}</p>}
</div>
</div>
</div>
);

constRiskBadge=({level}:{level:string})=>{
constcolors={low:'bg-green-100text-green-700',medium:'bg-orange-100text-orange-700',high:'bg-red-100text-red-700'};
constlabels={low:'LowRisk',medium:'MediumRisk',high:'HighRisk'};
return<spanclassName={`px-2.5py-1rounded-fulltext-xsfont-medium${colors[levelaskeyoftypeofcolors]||'bg-gray-100text-gray-700'}`}>{labels[levelaskeyoftypeoflabels]||level}</span>;
};

constTrendBadge=({trend}:{trend:string})=>{
constconfig={improving:{label:'Improving↑',color:'text-green-600bg-green-50'},stable:{label:'Stable→',color:'text-yellow-600bg-yellow-50'},declining:{label:'Declining↓',color:'text-red-600bg-red-50'}};
constc=config[trendaskeyoftypeofconfig]||config.stable;
return<spanclassName={`px-2py-1rounded-fulltext-xsfont-medium${c.color}`}>{c.label}</span>;
};

constRiskScoreDashboard=()=>{
constnavigate=useNavigate();
const[searchTerm,setSearchTerm]=useState('');
const[currentPage,setCurrentPage]=useState(1);
constitemsPerPage=10;

constsummary=getRiskSummary();
constriskDistributionData=getRiskDistribution();
constriskFactorsData=getRiskFactorsData();

consttableData=useMemo(()=>{
letdata=allRiskScores.map(risk=>{
conststudent=students.find(s=>s.id===risk.studentId);
return{
id:risk.studentId,
studentName:student?`${student.name}${student.lastName}`:'Unknown',
riskScore:risk.riskScore,
riskLevel:risk.riskLevel,
trend:risk.trend,
factors:risk.appliedRules,
weeklyScore:80,//Mock
presentationScore:85,//Mock
submissionStatus:'Good'//Mock
};
});

//Sortbyhighestriskscorefirst
data.sort((a,b)=>b.riskScore-a.riskScore);

if(searchTerm){
constlowerSearch=searchTerm.toLowerCase();
data=data.filter(item=>
item.id.toLowerCase().includes(lowerSearch)||
item.studentName.toLowerCase().includes(lowerSearch)
);
}

returndata;
},[searchTerm]);

consttotalPages=Math.ceil(tableData.length/itemsPerPage);
constcurrentData=tableData.slice((currentPage-1)*itemsPerPage,currentPage*itemsPerPage);

return(
<divclassName="space-y-6">
<div>
<h1className="text-2xlfont-boldtext-gray-800">LearningAnalyticsRiskScoreDashboard</h1>
<pclassName="text-gray-500">การวิเคราะห์ความเสี่ยงนักศึกษา</p>
</div>

<divclassName="gridgrid-cols-2md:grid-cols-5gap-6">
<SummaryCardicon={Users}title="นักศึกษาทั้งหมด"value={summary.totalStudents}color="bg-blue-600"/>
<SummaryCardicon={ShieldCheck}title="LowRisk"value={summary.lowRisk}subtitle={`${summary.lowPercentage}%`}color="bg-green-600"/>
<SummaryCardicon={AlertTriangle}title="MediumRisk"value={summary.mediumRisk}subtitle={`${summary.mediumPercentage}%`}color="bg-orange-500"/>
<SummaryCardicon={AlertCircle}title="HighRisk"value={summary.highRisk}subtitle={`${summary.highPercentage}%`}color="bg-red-500"/>
<SummaryCardicon={Users}title="RiskScoreเฉลี่ย"value={`${summary.averageRiskScore}/100`}color="bg-gray-600"/>
</div>

<divclassName="gridgrid-cols-1lg:grid-cols-2gap-6">
<divclassName="bg-whiterounded-xlshadow-smborderborder-gray-100p-6">
<h2className="text-lgfont-semiboldtext-gray-800mb-4">สัดส่วนระดับความเสี่ยง</h2>
<divclassName="h-64">
<DonutChartdata={riskDistributionData}/>
</div>
</div>
<divclassName="bg-whiterounded-xlshadow-smborderborder-gray-100p-6">
<h2className="text-lgfont-semiboldtext-gray-800mb-4">ปัจจัยที่ส่งผลต่อความเสี่ยง</h2>
<divclassName="h-64">
<BarChartComponentdata={riskFactorsData}/>
</div>
</div>
</div>

<divclassName="bg-whiterounded-xlshadow-smborderborder-gray-100overflow-hidden">
<divclassName="p-6border-bborder-gray-100flexflex-colsm:flex-rowjustify-betweenitems-startsm:items-centergap-4">
<h2className="text-lgfont-semiboldtext-gray-800">รายชื่อนักศึกษาตามระดับความเสี่ยง</h2>
<divclassName="relative">
<input
type="text"
placeholder="ค้นหารหัสนักศึกษา,ชื่อ..."
value={searchTerm}
onChange={(e)=>{setSearchTerm(e.target.value);setCurrentPage(1);}}
className="pl-10pr-4py-2borderborder-gray-300rounded-lgtext-smfocus:outline-nonefocus:border-blue-500w-fullsm:w-64"
/>
<SearchclassName="w-4h-4text-gray-400absoluteleft-3top-2.5"/>
</div>
</div>

<divclassName="overflow-x-auto">
<tableclassName="w-fulltext-leftborder-collapse">
<thead>
<trclassName="bg-gray-50text-gray-600text-smborder-bborder-gray-100">
<thclassName="p-4font-medium">ลำดับ</th>
<thclassName="p-4font-medium">รหัสนักศึกษา</th>
<thclassName="p-4font-medium">ชื่อ-สกุล</th>
<thclassName="p-4font-medium">RiskScore</th>
<thclassName="p-4font-medium">ระดับความเสี่ยง</th>
<thclassName="p-4font-medium">Trend</th>
<thclassName="p-4font-mediumw-1/4">ปัจจัยเสี่ยง</th>
<thclassName="p-4font-medium">Weekly</th>
<thclassName="p-4font-medium">Presentation</th>
<thclassName="p-4font-medium">Submission</th>
<thclassName="p-4font-mediumtext-center">การดำเนินการ</th>
</tr>
</thead>
<tbody>
{currentData.length>0?currentData.map((item,index)=>(
<trkey={item.id}className="border-bborder-gray-50hover:bg-gray-50transition-colorsgroup"title="คลิกปุ่มดำเนินการเพื่อดูคำแนะนำ">
<tdclassName="p-4text-smtext-gray-600">{(currentPage-1)*itemsPerPage+index+1}</td>
<tdclassName="p-4text-smfont-mediumtext-gray-800">{item.id}</td>
<tdclassName="p-4text-smtext-gray-600">{item.studentName}</td>
<tdclassName="p-4text-smfont-boldtext-gray-800">{item.totalScore}</td>
<tdclassName="p-4">
<RiskBadgelevel={item.finalLevel}/>
</td>
<tdclassName="p-4">
<TrendBadgetrend={item.trend}/>
</td>
<tdclassName="p-4text-xstext-gray-600">
<ulclassName="list-discpl-4">
{item.factors.slice(0,2).map((factor:any,i:number)=>(
<likey={i}className="truncate">{factor.ruleName}</li>
))}
{item.factors.length>2&&<li>และอื่นๆ...</li>}
</ul>
</td>
<tdclassName="p-4text-smtext-gray-600">{item.weeklyScore}</td>
<tdclassName="p-4text-smtext-gray-600">{item.presentationScore}</td>
<tdclassName="p-4text-smtext-gray-600">{item.submissionStatus}</td>
<tdclassName="p-4text-center">
<button
onClick={()=>navigate(`/student/${item.id}`)}
className="p-1.5text-blue-600hover:bg-blue-50rounded-lgtransition-colors"
>
<EyeclassName="w-5h-5"/>
</button>
</td>
</tr>
)):(
<tr>
<tdcolSpan={11}className="p-8text-centertext-gray-500">
ไม่พบข้อมูล
</td>
</tr>
)}
</tbody>
</table>
</div>

{totalPages>1&&(
<divclassName="p-4border-tborder-gray-100flexitems-centerjustify-between">
<spanclassName="text-smtext-gray-500">
แสดง{(currentPage-1)*itemsPerPage+1}ถึง{Math.min(currentPage*itemsPerPage,tableData.length)}จาก{tableData.length}รายการ
</span>
<divclassName="flexitems-centergap-2">
<button
onClick={()=>setCurrentPage(prev=>Math.max(prev-1,1))}
disabled={currentPage===1}
className="p-1rounded-lgborderborder-gray-200text-gray-600disabled:opacity-50disabled:cursor-not-allowedhover:bg-gray-50"
>
<ChevronLeftclassName="w-5h-5"/>
</button>
<spanclassName="text-smtext-gray-600font-mediumpx-2">
หน้า{currentPage}/{totalPages}
</span>
<button
onClick={()=>setCurrentPage(prev=>Math.min(prev+1,totalPages))}
disabled={currentPage===totalPages}
className="p-1rounded-lgborderborder-gray-200text-gray-600disabled:opacity-50disabled:cursor-not-allowedhover:bg-gray-50"
>
<ChevronRightclassName="w-5h-5"/>
</button>
</div>
</div>
)}
</div>
</div>
);
};

exportdefaultRiskScoreDashboard;
